### ISSUE TITLE
Animated GIFs in Image Results

### ISSUE THREAD

**Issue by lhami** [kumeS/GoogleImage2Array#1]
Hey! Really cool little package, I'm enjoying playing around with it.

I ran into an issue trying to get the results for the query "orange", with the following error:
```
Error in readJPEG(x, ...) : 
  JPEG decompression error: Not a JPEG file: starts with 0x89 0x50
```
Looking at [the google search results page for orange](https://www.google.com/search?tbm=isch&q=orange), it looks like there are some images which are .png files and not .jpeg, but I think the problem is likely [an animated gif](https://dktix1rrcd7mv.cloudfront.net/legacy/Images/Blog/TCM_NSAW_Basketball.gif).

Not knowing how the package is coded, my first instinct is to suggest that the package might be able to skip over results that are animated? Alternatively, in the browser, I know you can set some format/file type settings for the search. I don't know how accessible that would be for the package.

**Comment by kumeS** [comment]
Hi, @lhami. Thank you for your kind comment!!
I am aware of the error you reported, but it is not reproducible because the search results often change. 
For now, as a workaround, this function 'GoogleImage2array' allows users to set the gl parameter (country to search), so try temporarily changing **the gl parameter from us (default) to another country (e.g. Canada "ca", United Kingdom "uk")** and run the search. I hope to correct this error in the future / next update.

> #Version: 0.99.2
>remove.packages("GoogleImage2Array")
>install.packages(c("devtools", "BiocManager"), repos="http://cran.r-project.org")
>BiocManager::install("EBImage")
>
>install.packages("GoogleImage2Array", dependencies = TRUE)
>library(GoogleImage2Array)
>packageVersion("GoogleImage2Array")
>
>#Search images (Default: us)
>Query <- "orange"
>Img1 <- GoogleImage2array(Query, gl="us")
>display.array(Img1)
>
>#Canada
>ImgCa <- GoogleImage2array(Query, gl="ca")
>display.array(ImgCa)
>
>#UK
>ImgGb <- GoogleImage2array(Query, gl="gb")
>display.array(ImgGb)
>
>#Version: 0.99.7
>remove.packages("GoogleImage2Array")
>devtools::install_github("kumeS/GoogleImage2Array")
>library(GoogleImage2Array)
>packageVersion("GoogleImage2Array")
>
>#Search images (Default: us)
>query <- "orange"
>Img2 <- GoogleImage2array(query, gl="us")
>display.array(Img2)
>
>#UK
>ImgGb2 <- GoogleImage2array(Query, gl="gb")
>display.array(ImgGb2)

**Comment by kumeS** [comment]
Today I checked the below code and it worked well.

>library(GoogleImage2Array)
>#Search images (Default: us)
>Query <- "orange"
>Img1 <- GoogleImage2array(Query, gl="us")
>display.array(Img1)

**Comment by kumeS** [comment]
<img width="1223" alt="スクリーンショット 2022-03-21 17 34 38" src="https://user-images.githubusercontent.com/10130812/159227298-7b749c4b-20fd-481b-b9a7-c7de41f67c9c.png">

**Comment by kumeS** [comment]
<img width="1218" alt="スクリーンショット 2022-03-21 17 23 18" src="https://user-images.githubusercontent.com/10130812/159227348-53569a0f-b223-4ae0-91e0-d567b147c877.png">

**Comment by kumeS** [comment]
<img width="1233" alt="スクリーンショット 2022-03-21 17 36 04" src="https://user-images.githubusercontent.com/10130812/159227498-f8cfe050-9e86-4817-9b56-fe6afc3051d5.png">
